### ISSUE TITLE
cannot start mumo probably a python problem

### ISSUE THREAD

**Issue by Stunner1984** [mumble-voip/mumo#5]
mumo@Downwind:~/mumo$ service mumo start
Traceback (most recent call last):
  File "/home/mumo/mumo/mumo.py", line 43, in <module>
    from optparse   import OptionParser
  File "/usr/lib/python2.7/optparse.py", line 419, in <module>
    _builtin_cvt = { "int" : (_parse_int, _("integer")),
  File "/usr/lib/python2.7/gettext.py", line 581, in gettext
    return dgettext(_current_domain, message)
  File "/usr/lib/python2.7/gettext.py", line 545, in dgettext
    codeset=_localecodesets.get(domain))
  File "/usr/lib/python2.7/gettext.py", line 480, in translation
    mofiles = find(domain, localedir, languages, all=1)
  File "/usr/lib/python2.7/gettext.py", line 437, in find
    for nelang in _expand_lang(lang):
  File "/usr/lib/python2.7/gettext.py", line 131, in _expand_lang
    from locale import normalize
ImportError: cannot import name normalize

just looking for guidance, not sure if python changed something and I didn't catch it, thanks.

**Comment by Stunner1984** [comment]
Was not a mumo issue did a sudo apt-get install --reinstall python2.7 fixed it, thanks.
